const phases=[
 {id:'phase-1',number:'01',title:'ML foundations & problem framing',subtitle:'Learn what a model can and cannot promise before training a single one.',modules:[
  {n:1,title:'What is machine learning?',desc:'Separate ML from rules and statistics, and learn generalization as the actual goal.',next:false,builtCount:10,concepts:['What is machine learning?','Supervised versus unsupervised versus reinforcement learning','Why generalization is the actual goal','Overfitting and underfitting','The bias-variance tradeoff','Train, validation and test splits','Baselines and why they matter','Leakage — the silent killer','The ML problem-framing checklist','When not to use ML']},
  {n:2,title:'Evaluation metrics fundamentals',desc:'Choose a metric that actually reflects the business problem, not just a library default.',next:false,builtCount:10,concepts:['Why accuracy lies','The confusion matrix from first principles','Precision, recall and F1','ROC-AUC and PR-AUC','Regression metrics — MAE, RMSE and R²','Calibration — what a probability actually means','Choosing a metric for a business problem','Metric-target misalignment and Goodhart’s law','Statistical versus practical significance','Worked case — choosing CFPB Model 1’s metric']}
 ]},
 {id:'phase-2',number:'02',title:'Data & feature engineering',subtitle:'Turn raw records into leakage-free, model-ready features.',modules:[
  {n:3,title:'Exploratory data analysis',desc:'Diagnose a dataset before trusting any model trained on it.',next:true,builtCount:10,concepts:['EDA as a discipline, not a checklist','Univariate and bivariate analysis','Missing data mechanisms — MCAR, MAR and MNAR','Outlier detection','Distribution-shift red flags','Correlation versus causation traps','Diagnosing class imbalance early','Cardinality and its consequences','Temporal leakage in EDA','Worked case — CFPB’s real EDA findings']},
  {n:4,title:'Feature engineering',desc:'Build features that add signal without smuggling in the answer.',concepts:['What makes a feature “good”','Encoding categorical variables','High-cardinality encoding — out-of-fold target encoding','Numerical scaling and transforms','Datetime and temporal features','Interaction and derived features','Feature engineering versus feature leakage','Feature selection methods','Missing values as a feature decision','Worked case — CFPB’s leakage-free intake features']},
  {n:5,title:'Imbalanced data',desc:'Train and evaluate correctly when the outcome you care about is rare.',concepts:['Why imbalance breaks naive training','Resampling — oversampling, undersampling and SMOTE','Class weighting','Threshold moving versus resampling','Cost-sensitive learning','Evaluation under imbalance','Imbalance in classical ML versus deep learning','Production consequences of imbalance choices','Worked case — CFPB’s product-varying relief rate']}
 ]},
 {id:'phase-3',number:'03',title:'Core supervised algorithms',subtitle:'The models that do most of the real work in production tabular and text ML.',modules:[
  {n:6,title:'Linear and logistic regression',desc:'The interpretable baseline every later model has to beat.',concepts:['Linear regression from first principles','Ordinary least squares — the math','Ridge and lasso regularization','Logistic regression and the sigmoid','Odds, log-odds and coefficients','Decision boundaries — geometric intuition','Linear and quadratic discriminant analysis','Multiclass extensions','Softmax and multiclass cross-entropy','When linear models win','Assumptions and their violations','Worked case — a logistic baseline for CFPB relief prediction']},
  {n:7,title:'Instance-based & probabilistic models',desc:'Distance-based and probability-based classifiers, and where each still wins.',concepts:['K-nearest neighbors and the curse of dimensionality','Distance metrics and their consequences','Naive Bayes and the independence assumption','Naive Bayes for text classification','Gaussian, multinomial and Bernoulli variants','Support vector machines — margins and kernels','The kernel trick, conceptually','Complexity versus interpretability tradeoffs','When these models still win','Worked case — a naive Bayes baseline for CFPB narrative tagging']},
  {n:8,title:'Decision trees & ensembles',desc:'From a single tree to the gradient-boosted models that power most tabular ML.',concepts:['Decision trees — splits and impurity measures','Overfitting in trees — depth and pruning','Bagging — bootstrap aggregation','Random forests — decorrelating trees','Feature importance from trees','Boosting — the sequential-correction idea','AdaBoost — weighted resampling','Gradient boosting — fitting residuals','XGBoost versus LightGBM — what’s actually different','Stacking and blending heterogeneous models','Hyperparameters that matter most','Worked case — gradient boosting for CFPB’s relief-risk model']},
  {n:9,title:'Neural networks & MLPs',desc:'The next step beyond linear models — stacked nonlinear transformations — without going into deep learning, sequence models or transformers.',concepts:['From linear models to a network of them','The perceptron and its limits','The multilayer perceptron — architecture','Activation functions — sigmoid, tanh and ReLU','Weight initialization and the vanishing/exploding gradient problem','Forward propagation, traced by hand','Backpropagation — the chain rule, conceptually','Gradient descent variants — SGD, momentum, RMSprop and Adam','Loss functions for classification and regression','Training dynamics — learning rate, epochs and batches','Overfitting in neural networks — dropout and regularization','Batch normalization','When an MLP beats gradient boosting, and when it doesn’t','Worked case — would an MLP actually help CFPB’s relief-risk model?']},
  {n:10,title:'Text data as a feature domain',desc:'Enough classical NLP to ship a real text classifier, and the bridge into learned embeddings.',concepts:['Text as a feature source — what changes','Text cleaning and normalization','Bag-of-words and the sparsity problem','TF-IDF — derivation and intuition','Classical text classifiers, reused','N-grams and their tradeoffs','When TF-IDF is enough','Embeddings — learned dense representations, beyond TF-IDF','The escalation point — when fine-tuning is worth it','Worked case — a TF-IDF baseline for CFPB’s narrative auto-triage']}
 ]},
 {id:'phase-4',number:'04',title:'Unsupervised & other paradigms',subtitle:'Structure discovery, dimensionality, and the outliers no classifier was trained on.',modules:[
  {n:11,title:'Clustering',desc:'Discover structure in data with no labels to check against.',concepts:['Why cluster — unsupervised structure discovery','K-means — mechanics and limitations','Choosing k — elbow and silhouette methods','Hierarchical clustering','DBSCAN — density-based clustering','Gaussian mixture models — soft, probabilistic clustering','Evaluating clusters without ground truth','When clustering misleads','Worked case — segmenting CFPB complaint types']},
  {n:12,title:'Dimensionality reduction',desc:'Compress high-dimensional data without discarding the signal that matters.',concepts:['The curse of dimensionality','PCA — variance and principal components','Explained variance and choosing components','PCA’s linear-projection limitation','t-SNE — local structure and its caveats','UMAP — what changed from t-SNE','Reduction for visualization versus modeling','Worked case — visualizing CFPB narrative embeddings']},
  {n:13,title:'Anomaly detection',desc:'Find the records no classifier was ever trained to recognize.',concepts:['What makes anomaly detection different from classification','Statistical outlier methods','Isolation forests','One-class SVM','Anomaly detection with imbalanced-style evaluation','Where anomaly detection fits a production system','Worked case — flagging unusual complaint patterns']}
 ]},
 {id:'phase-5',number:'05',title:'Evaluation, tuning & reliability',subtitle:'Make a model trustworthy, not just accurate on one split.',modules:[
  {n:14,title:'Cross-validation & experimental design',desc:'Measure a model honestly, including when time itself is a leakage risk.',concepts:['Why a single train/test split isn’t enough','K-fold cross-validation','Stratified k-fold','Temporal splits — why shuffling breaks them','Time series forecasting basics — trend, seasonality and a naive baseline','Nested cross-validation','Leakage through cross-validation itself','Statistically comparing models','Worked case — CFPB’s temporal split and TimeSeriesSplit']},
  {n:15,title:'Hyperparameter tuning',desc:'Search a model’s configuration space without overfitting the search itself.',concepts:['Manual tuning versus systematic search','Grid search — exhaustive and expensive','Random search — why it often wins','Bayesian optimization, intuitively','Optuna in practice','Search-space design','Overfitting the validation set','Worked case — Optuna-tuned XGBoost for CFPB']},
  {n:16,title:'Calibration & interpretability',desc:'Make probabilities mean something, and explain predictions to a real stakeholder.',concepts:['What probability calibration actually means','Reliability diagrams','Platt scaling and isotonic regression','Why calibration matters for thresholds','SHAP values from first principles','SHAP for tree models versus other models','Global versus local interpretability','Interpretability versus regulatory requirements','Worked case — SHAP explanations for CFPB’s relief predictions']},
  {n:17,title:'Drift & monitoring',desc:'Notice when a production model has quietly stopped matching the world.',concepts:['What model drift actually is','Data drift versus concept drift','Detecting drift statistically','Evidently and drift monitoring in practice','Retraining triggers — when and how','Monitoring beyond accuracy','Worked case — CFPB’s weekly-pull drift monitoring']}
 ]},
 {id:'phase-6',number:'06',title:'Production ML & lifecycle',subtitle:'Close the loop from experiment to a served, monitored, retrainable system.',modules:[
  {n:18,title:'Experiment tracking & model registry',desc:'Make every model version reproducible and comparable, not just the latest one.',concepts:['Why experiment tracking exists','MLflow — runs, experiments and artifacts','The model registry — versioning and stages','Reproducibility — what it actually requires','Comparing experiments systematically','Worked case — CFPB’s MLflow tracking']},
  {n:19,title:'Deployment & serving',desc:'Turn a trained model into a real, callable service.',concepts:['Batch versus online inference','Serving with FastAPI','Containerization — why Docker','Deployment targets — cloud versus self-hosted','Latency and throughput tradeoffs','API design for ML services','Worked case — CFPB’s FastAPI, Docker and Azure deployment']},
  {n:20,title:'CI/CD & production reliability',desc:'Keep a deployed model honest, tested, and safely rollback-able over time.',concepts:['Why ML needs its own CI/CD thinking','Testing ML code versus testing ML models','GitHub Actions for retraining pipelines','Rollback strategies for models','Logging and observability for ML systems','The full lifecycle, closed — EDA to monitoring','Capstone synthesis — CFPB Model 1 and Model 2, end to end']}
 ]}
];

const phasesRoot=document.querySelector('#phases');
function moduleMarkup(module){const modId=String(module.n).padStart(2,'0');const id=`module-${modId}`;const built=module.builtCount||0;const concepts=module.concepts.map((concept,index)=>{const isBuilt=index<built;const isActive=module.next&&index===built-1;const done=isBuilt&&!isActive;const href=isBuilt?`lessons/module-${modId}-concept-${String(index+1).padStart(2,'0')}.html`:'';const label=done?'Complete':isActive?'Open lesson':'Planned';const content=href?`<a class="concept-link" href="${href}"><b>${concept}</b></a>`:`<b>${concept}</b>`;return `<li class="${done?'completed-concept':isActive?'next-concept':''}"><span>${String(index+1).padStart(2,'0')}</span>${content}<em>${label}</em></li>`}).join('');return `<article class="roadmap-module ${module.next?'next-module':''}" id="${id}"><button class="module-summary" aria-expanded="${module.next?'true':'false'}"><span class="module-number">${modId}</span><span class="module-copy"><small>${module.next?'ACTIVE MODULE':'PLANNED MODULE'} · ${module.concepts.length} CONCEPTS</small><b>${module.title}</b><p>${module.desc}</p></span><span class="module-state">${module.next?'Open':'Planned'}</span><i>+</i></button><div class="concept-plan"><div class="concept-heading"><span>CONCEPT-BY-CONCEPT PLAN</span><small>Each item becomes a separate HTML lesson when reached.</small></div><ol>${concepts}</ol></div></article>`}
phasesRoot.innerHTML=phases.map(phase=>`<section class="phase-block reveal" id="${phase.id}"><header class="phase-header"><span>${phase.number}</span><div><small>PHASE ${phase.number} · ${phase.modules.length} MODULE${phase.modules.length>1?'S':''}</small><h2>${phase.title}</h2><p>${phase.subtitle}</p></div></header><div class="phase-modules">${phase.modules.map(moduleMarkup).join('')}</div></section>`).join('');
const moduleButtons=[...document.querySelectorAll('.module-summary')];
moduleButtons.forEach(button=>button.addEventListener('click',()=>{const module=button.closest('.roadmap-module');const open=module.classList.toggle('open');button.setAttribute('aria-expanded',String(open))}));
document.querySelector('.next-module')?.classList.add('open');
const expandButton=document.querySelector('#expandAll');let expanded=false;
expandButton?.addEventListener('click',()=>{expanded=!expanded;document.querySelectorAll('.roadmap-module').forEach(module=>{module.classList.toggle('open',expanded);module.querySelector('button').setAttribute('aria-expanded',String(expanded))});expandButton.textContent=expanded?'Collapse all':'Expand all'});
