const phases=[
 {id:'phase-1',number:'01',title:'Generative AI & retrieval foundations',subtitle:'Learn the model, mathematics, and search machinery RAG is built upon before assembling it.',modules:[
  {n:1,title:'Generative AI foundations',desc:'Understand the broader field, the model lifecycle, and why generated output differs from retrieved or computed output.',next:false,builtCount:8,concepts:['What is Generative AI?','Discriminative versus generative modelling','Major generative model families','Foundation models and large language models','Training, fine-tuning and inference','Tokens and modalities','Prompts, sampling and generated output','Capabilities, limitations and responsible use']},
  {n:2,title:'LLM & transformer foundations for RAG',desc:'Understand how language models represent input, use context, and produce grounded or ungrounded text.',next:false,builtCount:11,concepts:['What is a large language model?','Tokens and tokenization in depth','Transformer architecture overview','Self-attention—conceptual understanding and positional information','Next-token probability and decoding','LLM training versus inference: pretraining, tuning and alignment','Context windows and in-context learning','Prompting principles and prompt roles','LLM knowledge limitations, parametric knowledge and hallucination','Attention dilution and lost-in-the-middle effects','Structured generation and constrained outputs']},
  {n:3,title:'RAG mental model & problem framing',desc:'Define the architecture, its purpose, its boundaries, and the problems it should—or should not—solve.',next:false,builtCount:12,concepts:['What exactly is Retrieval-Augmented Generation?','Why we cannot simply ask the LLM: external knowledge','Knowledge cutoffs, private company knowledge and frequently changing information','Hallucination reduction, grounding and provenance','Parametric and non-parametric memory','The offline indexing and online query pipelines','RAG versus prompting and long-context prompting','RAG versus fine-tuning, search and tool use','Naive, advanced and modular RAG taxonomy','Knowledge-intensive tasks and answerability','The RAG failure chain','When RAG should not be used']},
  {n:4,title:'Mathematics for retrieval',desc:'Build the linear algebra, probability, and optimization intuition needed to reason about retrieval systems.',next:false,builtCount:10,concepts:['Scalars, vectors and matrices','Vector norms, dimensions and normalization','Dot product, vector similarity, angles and cosine similarity','Euclidean and other distance functions','Probability and conditional probability','Softmax, temperature and logarithms','Entropy and cross-entropy','Ranking functions and optimization objectives','Time and space complexity','Worked retrieval geometry']},
  {n:5,title:'Classical information retrieval',desc:'Learn the lexical-search foundations that dense retrieval extends rather than replaces.',next:false,builtCount:11,concepts:['What is information retrieval? Corpora, documents, queries and relevance','Inverted indexes and postings lists','Sparse retrieval and dense retrieval','Term frequency and inverse document frequency','TF–IDF derivation','BM25 derivation and parameters','Document-length normalization','Precision, recall and F-score','MRR, MAP, DCG and nDCG','Relevance judgments and test collections','Lexical retrieval strengths and failures']}
 ]},
 {id:'phase-2',number:'02',title:'Building the knowledge layer',subtitle:'Transform heterogeneous source material into faithful, searchable representations.',modules:[
  {n:6,title:'Knowledge sources & ingestion',desc:'Acquire, parse, clean, version, and trace the information the system will rely upon.',builtCount:9,concepts:['Source inventory and authority','PDF, HTML, Word, Excel and Markdown parsing','Databases, APIs, tickets and code repositories','OCR, layout, tables and images','Cleaning and normalization','Deduplication and canonicalization','Document identity and versioning','Provenance, lineage and timestamps','Incremental and event-driven ingestion']},
  {n:7,title:'Chunking & document representation',desc:'Design retrieval units that preserve meaning without drowning useful evidence in noise.',next:false,builtCount:10,concepts:['Why chunk documents?','Fixed-size and recursive chunking','Sentence, paragraph and structural chunking','Semantic and proposition-based chunking','Chunk size as a precision–context trade-off','Chunk overlap and boundary loss','Parent-document, parent–child and small-to-big retrieval','Hierarchical and late chunking','Metadata and contextual headers','Evaluating chunk quality']},
  {n:8,title:'Embeddings & representation learning',desc:'Understand how text becomes geometry and how embedding choices shape retrievable meaning.',next:false,builtCount:11,concepts:['What is an embedding?','Text-to-vector semantic representation','Bi-encoders and asymmetric query embeddings versus document embeddings','Contrastive learning objectives','Positive pairs, negatives and hard negatives','Pooling, embedding dimensions and normalization','Anisotropy and embedding-space pathologies','Embedding-model instructions and query/document prefixes','Multilingual and domain embedding models','Embedding-model selection','Versioning, drift and migration']},
  {n:9,title:'Vector indexes & vector databases',desc:'Scale similarity search while understanding every approximation and operational trade-off.',next:false,builtCount:10,concepts:['Exact vector similarity search','Approximate nearest-neighbour vector search','HNSW graph construction and search','IVF partitioning','Product and scalar quantization','Recall–latency–memory trade-offs','Metadata filtering strategies','Updates, deletes and tombstones','Replication, sharding and consistency','Capacity planning and benchmarking']},
  {n:10,title:'RAG databases & vector-store implementation',desc:'Turn database-independent retrieval theory into secure, testable implementations, with Oracle as the primary course path.',next:false,builtCount:14,concepts:['Vector store versus vector database versus search engine','What the database owns in a RAG architecture','Schema design for documents, versions, chunks, embeddings and citations','Metadata, tenant and authorization filters in SQL','Oracle AI Database VECTOR type and vector-distance SQL','Exact search and Oracle vector indexes','Oracle Text and vector hybrid retrieval','Python integration with python-oracledb','Transactions, updates, deletes and index synchronization','Oracle security and operational considerations for RAG','PostgreSQL and pgvector portability comparison','Managed and specialist stores: Pinecone, Qdrant, Weaviate and Milvus','Choosing a store by workload, governance, scale and cost','Retrieval-store interfaces and database portability lab']}
 ]},
 {id:'phase-3',number:'03',title:'The online RAG pipeline',subtitle:'Connect retrieval and generation, then improve every decision made at query time.',modules:[
  {n:11,title:'Baseline RAG from first principles',desc:'Construct the smallest complete RAG system and trace one query through every transformation.',next:true,concepts:['End-to-end basic RAG pipeline and architecture','Document ingestion and index construction workflow','Document chunking and embedding flow','Vector database and vector-store persistence','Query embedding, retrieval and candidate search','Top-k evidence selection','Context injection, context construction and prompt construction','LLM generation and the final answer','Source identifiers and citations','Conversation history','End-to-end framework-free implementation']},
  {n:12,title:'LangChain for RAG',desc:'Use LangChain’s component and integration layer after understanding the framework-free pipeline it represents.',concepts:['Why use LangChain—and when not to','Installation, packages, versions and provider integrations','Models, messages, prompts and structured output','Documents, loaders and document metadata','Text splitters and ingestion composition','Embedding models and vector-store integrations','Retriever interface and retriever composition','Runnables, chains and data flow','Two-step RAG in LangChain','Retrieval tools and agentic RAG','Hybrid and self-correcting RAG patterns','Streaming, batching, async and callbacks','Testing, serialization and framework escape hatches','Rebuilding the baseline pipeline with LangChain']},
  {n:13,title:'LangGraph for stateful RAG orchestration',desc:'Model controlled, persistent and recoverable retrieval workflows as explicit state, nodes and transitions.',concepts:['When LangGraph is justified—and when a chain is enough','State schemas, channels and reducers','Nodes, edges, START, END and compilation','Conditional routing and query classification','Loops, recursion limits, budgets and stopping conditions','Parallel branches, subgraphs and map-reduce patterns','Checkpoints, threads and persistence','Durable execution, retries and fault recovery','Streaming graph events and partial outputs','Interrupts and human-in-the-loop review','Short-term state, long-term memory and RAG knowledge','Tool nodes and multi-source retrieval','Corrective and agentic RAG graphs','Testing state transitions and deterministic replay','Tracing and debugging LangGraph executions','Building a bounded research workflow']},
  {n:14,title:'RAG ecosystem, observability & interoperability',desc:'Compare surrounding frameworks and standards, observe executions, and avoid locking architectural judgment to one library.',concepts:['Framework-neutral ports and adapters','LangSmith traces, datasets, experiments and monitoring','LlamaIndex ingestion, indexes, retrievers and query engines','Haystack components, pipelines and document stores','Microsoft GraphRAG package versus the GraphRAG architecture','MCP resources, tools and external knowledge integrations','Provider and model abstraction boundaries','Callbacks, telemetry and OpenTelemetry concepts','Prompt, model, retriever and index version tracking','Framework comparison by control, maturity and workload','Migration and interoperability strategies','Version-aware implementation and dependency risk','When to implement directly instead of adding a framework']},
  {n:15,title:'Query understanding & transformation',desc:'Turn imperfect user language into effective, controlled information-seeking operations.',concepts:['Intent and answer-type recognition','Standalone-query rewriting','Query expansion','Question decomposition and subqueries','Multi-query retrieval','Step-back prompting','Hypothetical Document Embeddings','Contextual retrieval','Self-query and metadata-aware retrieval','Recursive and multi-hop retrieval','Query routing','Ambiguity and query-drift control']},
  {n:16,title:'Advanced retrieval, fusion & reranking',desc:'Combine complementary signals, improve candidate precision, and control evidence diversity.',concepts:['Sparse and dense retrieval compared','Hybrid search and retrieval architectures','Why initial top-k retrieval is not enough','Top-k retrieval and similarity thresholds','Relevance scoring and score normalization','Reciprocal rank fusion','Weighted and learned fusion','Candidate generation versus reranking','Cross-encoder reranking','Late interaction and ColBERT','Maximal marginal relevance','Context compression and filtering','Authority, freshness and diversity signals','Retrieval relevance and failure diagnosis']},
  {n:17,title:'Context engineering & grounded generation',desc:'Build evidence-rich prompts that support precise, attributable, and appropriately uncertain answers.',concepts:['Context selection and ordering','Token budgeting and evidence packing','Duplicate removal and compression','Prompt boundaries and evidence isolation','Lost-in-the-middle mitigation','Claim-level citations','Faithfulness, groundedness and attribution','Conflicting evidence','Abstention and calibrated uncertainty','Structured outputs and citation validation']}
 ]},
 {id:'phase-4',number:'04',title:'Quality, reliability & operations',subtitle:'Make the system measurable, operable, secure, and worthy of user trust.',modules:[
  {n:18,title:'Evaluation & experimental science',desc:'Measure retrieval and generation independently, then test the entire user experience.',concepts:['Why RAG evaluation is difficult','Evaluation-dataset design','Queries, golden documents and expected claims','Retrieval evaluation: Precision@k, Recall@k, MRR and nDCG','Context precision, context recall and context relevance','Answer quality: correctness, completeness and answer relevance','Faithfulness, groundedness and hallucination evaluation','Citation precision and citation recall','RAGAS-style, ARES and other evaluation frameworks','LLM-as-judge and judge bias','Human evaluation','Ablations, error analysis and regression tests','Online experiments and product metrics']},
  {n:19,title:'Production architecture & RAG operations',desc:'Engineer for latency, cost, change, failures, deployment, and continuous improvement.',concepts:['Service boundaries and data flows','Synchronous and asynchronous pipelines','Latency decomposition and streaming','Caching and invalidation','Embedding and indexing cost','LLM inference and token cost','Retrieval cost and cost optimization','Retries, timeouts and circuit breakers','Observability, logging and distributed traces','Prompt, model and index versioning','Vector-database scaling and capacity','Load, stress and soak testing','Freshness and reliability SLOs','Document updates and incremental indexing','Provider-neutral deployment patterns','Index migrations and rollback','Production monitoring and continuous improvement']},
  {n:20,title:'Security, privacy & governance',desc:'Protect the corpus, retrieval layer, model context, output, and people affected by the system.',concepts:['Direct and indirect prompt injection','Poisoned documents and malicious metadata','Authorization-aware retrieval and access control','Tenant isolation, multi-tenancy and security trimming','PII, secrets and data minimization','Embedding, cache and log privacy','Source trust and provenance','Output controls and high-impact actions','Red teaming and incident response','Auditability, governance and compliance']}
 ]},
 {id:'phase-5',number:'05',title:'Advanced architectures',subtitle:'Extend retrieval beyond flat text without abandoning the principles of measurement and control.',modules:[
  {n:21,title:'Structured-data & knowledge-graph RAG',desc:'Retrieve facts and relationships from databases, APIs, and explicit graph structures.',concepts:['RAG over structured data','Text-to-SQL and safe query execution','API and tool-backed retrieval','Schema linking and routing','Entity extraction and resolution','Knowledge graphs and graph traversal','Multi-hop graph retrieval','Community detection and summaries','GraphRAG local, global and DRIFT search','Graph-plus-vector fusion','Structured and graph evaluation']},
  {n:22,title:'Multimodal RAG',desc:'Retrieve and ground answers in images, tables, diagrams, audio, and video.',concepts:['Why text-only RAG is insufficient','Multimodal documents and representations','Image and region embeddings','Table and chart retrieval','Layout-aware document retrieval','Audio and temporal retrieval','Video segmentation and search','Cross-modal ranking','Multimodal context construction','Modality-aware citations','Multimodal RAG evaluation']},
  {n:23,title:'Adaptive, corrective & agentic RAG',desc:'Design systems that decide when, where, and how often to retrieve while keeping loops bounded.',concepts:['Selecting among advanced, modular, corrective, adaptive and agentic architectures','RAG versus agentic RAG','Agent decides whether and when to retrieve','Retrieval-quality grading','Corrective RAG','Self-RAG and reflection tokens','Tool use and retrieval as a tool','Multiple retrieval sources','Iterative retrieval and multi-step reasoning','Planning and planner–retriever architectures','Tool selection and routing','Agent memory versus RAG','Budgets and stopping conditions','Error accumulation and agent evaluation']}
 ]},
 {id:'phase-6',number:'06',title:'Synthesis',subtitle:'Integrate the layers into one defensible, production-grade system.',modules:[
  {n:24,title:'Optimization & production capstone',desc:'Apply the complete discipline to design, evaluate, secure, and operate a real RAG product.',concepts:['Embedding adaptation and fine-tuning','Hard-negative mining','Reranker training and distillation','End-to-end optimization','Requirements and risk discovery','Architecture decision records','Threat modelling','Cost–quality–latency trade-offs','Benchmark and test-suite construction','Production system implementation','Launch-readiness review','Evolution and migration strategy']}
 ]}
];

window.ATLAS_PHASES=phases;
const phasesRoot=document.querySelector('#phases');
function moduleMarkup(module){const modId=String(module.n).padStart(2,'0');const id=`module-${modId}`;const built=module.builtCount||0;const concepts=module.concepts.map((concept,index)=>{const isBuilt=index<built;const isActive=module.next&&index===built-1;const done=isBuilt&&!isActive;const href=isBuilt?`lessons/module-${modId}-concept-${String(index+1).padStart(2,'0')}.html`:'';const label=done?'Complete':isActive?'Open lesson':'Planned';const content=href?`<a class="concept-link" href="${href}"><b>${concept}</b></a>`:`<b>${concept}</b>`;return `<li class="${done?'completed-concept':isActive?'next-concept':''}"><span>${String(index+1).padStart(2,'0')}</span>${content}<em>${label}</em></li>`}).join('');return `<article class="roadmap-module ${module.next?'next-module':''}" id="${id}"><button class="module-summary" aria-expanded="${module.next?'true':'false'}"><span class="module-number">${modId}</span><span class="module-copy"><small>${module.next?'ACTIVE MODULE':'PLANNED MODULE'} · ${module.concepts.length} CONCEPTS</small><b>${module.title}</b><p>${module.desc}</p></span><span class="module-state">${module.next?'Open':'Planned'}</span><i>+</i></button><div class="concept-plan"><div class="concept-heading"><span>CONCEPT-BY-CONCEPT PLAN</span><small>Each item becomes a separate HTML lesson when reached.</small></div><ol>${concepts}</ol></div></article>`}
if(phasesRoot){
phasesRoot.innerHTML=phases.map(phase=>`<section class="phase-block reveal" id="${phase.id}"><header class="phase-header"><span>${phase.number}</span><div><small>PHASE ${phase.number} · ${phase.modules.length} MODULE${phase.modules.length>1?'S':''}</small><h2>${phase.title}</h2><p>${phase.subtitle}</p></div></header><div class="phase-modules">${phase.modules.map(moduleMarkup).join('')}</div></section>`).join('');
const moduleButtons=[...document.querySelectorAll('.module-summary')];
moduleButtons.forEach(button=>button.addEventListener('click',()=>{const module=button.closest('.roadmap-module');const open=module.classList.toggle('open');button.setAttribute('aria-expanded',String(open))}));
document.querySelector('.next-module')?.classList.add('open');
const expandButton=document.querySelector('#expandAll');let expanded=false;
expandButton?.addEventListener('click',()=>{expanded=!expanded;document.querySelectorAll('.roadmap-module').forEach(module=>{module.classList.toggle('open',expanded);module.querySelector('button').setAttribute('aria-expanded',String(expanded))});expandButton.textContent=expanded?'Collapse all':'Expand all'});
}
if(typeof dispatchEvent==='function')dispatchEvent(new Event('atlasphasesready'));
